import type { Metadata } from "next";

/**
 * The brand assets that belong in a document head, in one place.
 *
 * `app/layout.tsx`, `app/speaker/layout.tsx` and `app/manifest.ts` all need
 * the same files, and Next's metadata objects do not merge deeply — a route
 * that sets `openGraph` at all replaces the parent's wholesale, images
 * included. Keeping the pieces here is what stops the hub and the landing
 * page drifting onto different icons.
 *
 * Everything referenced below is generated by `scripts/brand-icons.py` from
 * the artwork in `public/brand`. Edit the artwork and re-run the script; do
 * not hand-edit the output.
 */

/**
 * Absolute base for the URLs Next has to print in full.
 *
 * `og:image` is one of them: a relative path in that tag is simply ignored by
 * every scraper, so a preview card that works locally and silently disappears
 * in production is the default outcome without this.
 *
 * Vercel supplies the production hostname at build time, which covers the
 * deployment nobody configures by hand. `NEXT_PUBLIC_SITE_URL` overrides it
 * for a custom domain, where the `.vercel.app` hostname would otherwise be
 * the one pasted into every share.
 */
export const siteUrl = new URL(
  process.env.NEXT_PUBLIC_SITE_URL ||
    (process.env.VERCEL_PROJECT_PRODUCTION_URL || process.env.VERCEL_URL
      ? `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL || process.env.VERCEL_URL}`
      : "http://localhost:3000"),
);

/**
 * The icon set.
 *
 * `.ico` first and without a `type`: it is the one entry the oldest clients
 * understand, and it carries 16, 32 and 48 in the single file they ask for.
 * The PNGs after it are what anything current will prefer. The Apple entry is
 * separate because iOS ignores `rel="icon"` entirely when adding to the home
 * screen, and would fall back to a screenshot of the page.
 */
export const icons: Metadata["icons"] = {
  icon: [
    { url: "/favicon.ico", sizes: "16x16 32x32 48x48" },
    { url: "/icons/icon-32.png", type: "image/png", sizes: "32x32" },
    { url: "/icons/icon-192.png", type: "image/png", sizes: "192x192" },
    { url: "/icons/icon-512.png", type: "image/png", sizes: "512x512" },
  ],
  apple: { url: "/icons/apple-touch-icon.png", type: "image/png", sizes: "180x180" },
};

/** The 1200x630 card every link preview shows: the NeumoMeet 2026 lockup. */
export const socialPreview = {
  url: "/og/neumomeet.png",
  width: 1200,
  height: 630,
  alt: "NeumoMeet 2026 — Donde lo clínico y lo quirúrgico se encuentran",
} as const;
